version: "3"
services:
    apache:
        build:
            context: .
        depends_on:
          - mysql
        ports:
          - "5000:80"
        volumes:
          - .:/var/www/html/
    mysql:
        image: mysql:5.6.40
        ports:
          - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "rootpassword"
